language: python
python:
- '3.6'
sudo: required

before install:
    - chmod +x build.sh

before_script:
  - pip install matplotlib
  - pip install dm-sonnet
  - pip install python-coveralls
  - pip install pytest-cover
script:
  - ./install.sh
  - py.test test/ --cov=pyodds
