language: python
sudo: required
install:
  - git clone git@github.com:yli96/TDengine.git
  - cd TDengine/
  - mkdir build && cd build
  - cmake .. && cmake --build .
  - cd ..
  - pip install src/connector/python/linux/python3
  - sudo taosd & pip install -e .
before_script:
  - pip install matplotlib
  - pip install dm-sonnet
  - pip install python-coveralls
  - pip install pytest-cover
script:
  - py.test test/ --cov=pyodds